
version: '3'
services:

  site1:
    build:
      context: ./site1
      dockerfile: Dockerfile
    image: site1
    container_name: site1
    networks:
      - asa-network
  site2:
    build:
      context: ./site2
      dockerfile: Dockerfile
    image: site2
    container_name: site2
    networks:
      - asa-network
  site3:
    build:
      context: ./site3
      dockerfile: Dockerfile
    image: site3
    container_name: site3
    networks:
      - asa-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - site1
      - site2
      - site3
    networks:
      - asa-network

#Docker Networks
networks:
  asa-network:
    driver: bridge